micronaut:
  application:
    name: stockdataService


datasources:
  default:
    url: jdbc:h2:mem:devDb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2


#datasources:
#  default:
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: password
#    driverClassName: org.postgresql.Driver


jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
    entity-scan:
      packages: 'org.cerion.stocks'
